#
# Blog Settings
#

title: Blog Test


#
# Jekyll Settings
#

permalink: /archive/:year/:month/:day/:title/

gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap

feed:
  path: atom.xml
